#!/usr/bin/env python3
"""Convert an Apple Music/iTunes Library XML file into linked Markdown notes."""

from __future__ import annotations

import argparse
import json
import plistlib
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlsplit


INVALID_FILENAME = re.compile(r'[<>:"/\\|?*\x00-\x1f]')
WHITESPACE = re.compile(r"\s+")

# Obsidian global Graph View groups, in the order shown in the supplied image.
GRAPH_GROUPS = [
    ("tag:#Album", "#E65259"),
    ("tag:#Artist", "#E6B34E"),
    ("section:(fav)", "#AFE14C"),
    ("tag:#Year", "#C200D8"),
    ("tag:#Genre", "#55D9B7"),
    ("tag:#Track", "#B6C8D2"),
]


def clean_filename(value: object, fallback: str = "Untitled") -> str:
    """Return a portable, readable filename stem (without its extension)."""
    text = str(value or "").strip()
    text = INVALID_FILENAME.sub("_", text).rstrip(" .")
    text = WHITESPACE.sub(" ", text)
    return (text[:180].rstrip(" .") or fallback)


def markdown_text(value: object) -> str:
    """Keep metadata on one line and escape Markdown table/list hazards."""
    text = str(value).replace("\\", "\\\\").replace("\n", " ").replace("\r", " ")
    return text.replace("|", "\\|").strip()


def link_target(value: object, category: str, reserved: set[str], allocated: set[str]) -> str:
    base = clean_filename(value)
    candidate = base
    if candidate.casefold() in reserved or candidate.casefold() in allocated:
        candidate = clean_filename(f"{base} ({category})")
    suffix = 2
    original = candidate
    while candidate.casefold() in reserved or candidate.casefold() in allocated:
        candidate = f"{original} {suffix}"
        suffix += 1
    allocated.add(candidate.casefold())
    return candidate


def display_location(value: object) -> str:
    """Decode URL escapes for display while preserving a useful file path."""
    raw = str(value)
    parts = urlsplit(raw)
    if parts.scheme.lower() == "file":
        path = unquote(parts.path)
        if parts.netloc and parts.netloc != "localhost":
            path = f"//{parts.netloc}{path}"
        return path
    return unquote(raw)


def write_graph_groups(vault: Path) -> Path:
    """Install the requested groups in this vault's Obsidian graph settings."""
    config_path = vault / ".obsidian" / "graph.json"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    settings = {}
    if config_path.exists():
        with config_path.open("r", encoding="utf-8") as stream:
            settings = json.load(stream)
        if not isinstance(settings, dict):
            raise ValueError(f"Existing Graph View settings are not a JSON object: {config_path}")

    desired = [
        {"query": query, "color": {"a": 1, "rgb": int(color.lstrip("#"), 16)}}
        for query, color in GRAPH_GROUPS
    ]
    desired_queries = {group["query"] for group in desired}
    old_groups = settings.get("colorGroups", [])
    if not isinstance(old_groups, list):
        old_groups = []
    settings["colorGroups"] = desired + [
        group for group in old_groups
        if not isinstance(group, dict) or group.get("query") not in desired_queries
    ]
    with config_path.open("w", encoding="utf-8") as stream:
        json.dump(settings, stream, ensure_ascii=False, indent=2)
        stream.write("\n")
    return config_path


def load_tracks(xml_path: Path) -> list[dict]:
    with xml_path.open("rb") as stream:
        library = plistlib.load(stream)
    tracks = library.get("Tracks", {}) if isinstance(library, dict) else {}
    if not isinstance(tracks, dict):
        raise ValueError("The plist does not contain a valid Tracks dictionary.")
    result = []
    for key, track in tracks.items():
        if isinstance(track, dict):
            item = dict(track)
            item.setdefault("Track ID", key)
            result.append(item)
    return result


def make_notes(tracks: list[dict], output: Path) -> int:
    output.mkdir(parents=True, exist_ok=True)
    # Existing .md files are left alone unless their name is generated by this run.
    reserved: set[str] = set()
    track_stems: list[str] = []
    used_tracks = set(reserved)
    for track in tracks:
        base = clean_filename(track.get("Name"), "Untitled")
        stem = base
        track_id = track.get("Track ID", "")
        if stem.casefold() in used_tracks:
            tag = clean_filename(track.get("Artist") or track_id or "duplicate")
            stem = clean_filename(f"{base} - {tag}")
            number = 2
            original = stem
            while stem.casefold() in used_tracks:
                stem = f"{original} {number}"
                number += 1
        used_tracks.add(stem.casefold())
        track_stems.append(stem)

    # Allocate actual supporting pages for each linked value, avoiding track names.
    allocated: set[str] = set()
    targets: dict[tuple[str, str], str] = {}
    target_labels: dict[tuple[str, str], str] = {}
    fields = [("Artist", "Artist"), ("Album", "Album"), ("Year", "Release"),
              ("Genre", "Genre"), ("Favorited", "Fav")]
    for track in tracks:
        for field, category in fields:
            value = track.get(field)
            if value is None or value == "":
                continue
            page_value = ("Favorited" if value else "Not Favorited") if field == "Favorited" else str(value)
            normalized = page_value.casefold()
            key = (category, normalized)
            if key not in targets:
                targets[key] = link_target(page_value, category, used_tracks, allocated)
                target_labels[key] = page_value

    # Supporting notes make every wikilink resolve to a real Markdown file.
    for key, stem in targets.items():
        category = key[0]
        value = target_labels[key]
        tag = "Year" if category == "Release" else category
        (output / f"{stem}.md").write_text(
            f"# {markdown_text(value)}\n\n#{tag}\n", encoding="utf-8"
        )

    labels = [
        ("Track ID", "Track ID"), ("Name", "Name"), ("Artist", "Artist"),
        ("Album Artist", "Album Artist"), ("Composer", "Composer"),
        ("Album", "Album"), ("Genre", "Genre"), ("Track Number", "Track Number"),
        ("Track Count", "Track Count"), ("Disc Number", "Disc Number"),
        ("Disc Count", "Disc Count"), ("Year", "Year"),
        ("Date Added", "Date Added"), ("Date Modified", "Date Modified"),
        ("Release Date", "Release Date"), ("Total Time", "Duration (ms)"),
        ("Bit Rate", "Bit Rate (kbps)"), ("Sample Rate", "Sample Rate (Hz)"),
        ("Kind", "Kind"), ("Size", "Size (bytes)"), ("Persistent ID", "Persistent ID"),
    ]
    for track, stem in zip(tracks, track_stems):
        lines = [f"# {markdown_text(track.get('Name', 'Untitled'))}", "", "#Track", ""]
        prominent = [("Artist", "Artist"), ("Album", "Album"), ("Year", "Release"),
                     ("Genre", "Genre"), ("Favorited", "Fav")]
        for field, category in prominent:
            value = track.get(field)
            if value is None or value == "":
                continue
            target_value = ("Favorited" if value else "Not Favorited") if field == "Favorited" else str(value)
            target = targets[(category, target_value.casefold())]
            linked_label = "Fav" if field == "Favorited" else category
            lines.append(f"{linked_label} - [[{target}]]")
        lines += ["", "## Metadata", "", "| Field | Value |", "| --- | --- |"]
        for field, label in labels:
            value = track.get(field)
            if value not in (None, ""):
                lines.append(f"| {label} | {markdown_text(value)} |")
        if "Location" in track:
            lines.append(f"| Location | {markdown_text(display_location(track['Location']))} |")
        for field in ("Loved", "Favorited", "Purchased"):
            if field in track and field != "Favorited":
                lines.append(f"| {field} | {markdown_text(track[field])} |")
        (output / f"{stem}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(tracks)


def choose_paths() -> tuple[Path, Path] | None:
    """Open native dialogs to select the library XML and output folder."""
    try:
        import tkinter as tk
        from tkinter import filedialog, messagebox
    except ImportError as exc:
        raise RuntimeError(
            "Tkinter is unavailable. Install Python with Tk support or provide both paths on the command line."
        ) from exc

    root = tk.Tk()
    root.withdraw()
    root.update()
    try:
        input_name = filedialog.askopenfilename(
            title="Choose Apple Music/iTunes Library XML",
            filetypes=[("XML files", "*.xml"), ("All files", "*.*")],
        )
        if not input_name:
            return None
        output_name = filedialog.askdirectory(
            title="Choose a folder for Markdown notes",
            mustexist=False,
        )
        if not output_name:
            return None
        return Path(input_name), Path(output_name)
    finally:
        root.destroy()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert Apple Music/iTunes Library XML tracks into linked Markdown notes. "
                    "With no paths, open pickers for the input XML and output folder."
    )
    parser.add_argument("input_xml", nargs="?", type=Path, help="Apple Music/iTunes Library XML file")
    parser.add_argument("output_dir", nargs="?", type=Path, help="Directory for generated .md files")
    args = parser.parse_args()
    if bool(args.input_xml) != bool(args.output_dir):
        parser.error("provide both input_xml and output_dir, or omit both to use the file pickers")
    if args.input_xml is None:
        try:
            selected = choose_paths()
        except Exception as exc:
            parser.error(str(exc))
        if selected is None:
            print("Selection cancelled.", file=sys.stderr)
            return 1
        args.input_xml, args.output_dir = selected
    try:
        count = make_notes(load_tracks(args.input_xml), args.output_dir)
        graph_config = write_graph_groups(args.output_dir)
    except (OSError, plistlib.InvalidFileException, ValueError) as exc:
        parser.error(str(exc))
    print(f"Created {count} track notes and linked target notes in {args.output_dir}")
    print(f"Added Graph View groups in {graph_config}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
